### ISSUE TITLE
Laptop Room Microwave

### ISSUE THREAD

**Issue by bradsilcox** [familab/LabTasks#1]
Throw out black microwave, replace it with old one from old lab.

**Comment by hybridsix** [comment]
Has this been resolved?

**Comment by lancehudson** [comment]
## nope

Lance Hudson
Vice President
FamiLAB
lance@familab.org
PGP Key - keybase.io/lancehudson/key.asc
321-578-7228

~ FamiLAB’s mission is to be a community that fosters learning and creativity through hands-on projects, collaboration, and the sharing of skills & tools to improve ourselves and enrich the world around us. ~
