### ISSUE TITLE
Bathrooms

### ISSUE THREAD

**Issue by bradsilcox** [familab/LabTasks#10]
Bathroom Decor & Accessories
Soap dispensers (liquid soap or liquid soap foamers)
Toilet roll holders (non-mounted; 5 roll storage)
Wall mounted mirrors (I need this)
Trash cans

**Comment by DaveCasey** [comment]
Do we have a style in mind?
If I showed up with a couple of something like this:
http://www.amazon.com/Kimberly-Clark-Professional-ScottFold-Stainless-Dispenser/dp/B0040ZOE8A
or this
http://www.amazon.com/TrippNT-51912-Dispensing-Multi-Fold-Protective/dp/B004S7SPXK
and maybe this
http://www.amazon.com/Simply-Silver-Wall-Mount-Soap-Dispenser/dp/B00C19SDL6

on Saturday, would that be helpful?  Who should I work with regarding wall penetration?

**Comment by hybridsix** [comment]
Paper towel holders are already installed. :) We need some soap dispensers though, and toilet paper holders and such. We have some things that can be returned to home depot and ikea for store credit if you plan on visiting some of those stores. EDIT: I might be able to come by on saturday

**Comment by willasaywhat** [comment]
If we need anything in this realm I'm happy to pitch in or pick stuff up. Sounds like Dave has a plan though. I'll just wait and make it pretty afterwards. :p
