### ISSUE TITLE
Audio System

### ISSUE THREAD

**Issue by hybridsix** [familab/LabTasks#17]
System needs termination in Network/AV Closet. Some cables already there, some will need to be made, and some will need to be toned out. 

The room cables are not exposed at the moment, and need to be with a low-voltage cut in plate. 

Priority is to get speakers working again with a Bluetooth receiver. Maybe one for inside, one for outside to start with. 

Program needs to be written for X-Frame, and incorporate future wall controls and zones. Will include the 8802 for additional inputs.

**Comment by lancehudson** [comment]
lots of this is done, @hybridsix  is still working on final programming and additional inputs.

**Comment by npolanosky** [comment]
I believe this is complete or has stalled and is complete enough.
