### ISSUE TITLE
Refresh first aid kits

### ISSUE THREAD

**Issue by darkmoonsinger** [familab/LabTasks#22]
Most of our first aid kit supplies are expired.

**Comment by lancehudson** [comment]
Ill grab some refills next trip to costco

**Comment by darkmoonsinger** [comment]
I'll take a look at what we have left in the boxes and either tell Lance what to put on the costco list or just buy refills on Amazon. Expired meds are already cleaned out.

**Comment by npolanosky** [comment]
New first aid kit in black metal shop toolbox if needed.

**Comment by npolanosky** [comment]
Disregard closing, wrong button.

**Comment by npolanosky** [comment]
Has actually been restocked by Jamie and Lance
