### ISSUE TITLE
The lights in the warehouse are slowly burning out and everything is dimmer

### ISSUE THREAD

**Issue by willasaywhat** [familab/LabTasks#25]

**Comment by npolanosky** [comment]
The LED lights in the warehouse have completely stopped functioning. 
The relay still clicks but there are zero operable LED lights.

**Comment by hybridsix** [comment]
We're working on a solution - biggest challenge is cost of replacements right now. This was an option we looked at. It would(should) replace 2x of the LED lights. 

https://www.1000bulbs.com/product/173164/PLT-10242.html

**Comment by lancehudson** [comment]
Currently we don't have a plan forward on this that gives us a return on the investment within 2 years. Because of that we don't want to spend lab money on this right now.
