### ISSUE TITLE
Both fire extinguisher canisters in the fablab expired in January and need replaced

### ISSUE THREAD

**Issue by willasaywhat** [familab/LabTasks#32]

**Comment by willasaywhat** [comment]
Bakula: "You want an extinguisher that uses Halotron 1, unless you can get Halon 1211 (which is still available for aircraft applications, but priced accordingly.)"

**Comment by lancehudson** [comment]
Are we talking the small laser safe ones?

**Comment by npolanosky** [comment]
Yes

**Comment by lancehudson** [comment]
I think this is what we bought last time http://amzn.com/B00LN6S42G

**Comment by darkmoonsinger** [comment]
We just purchased a 5lb replacement laser-safe extinguisher; should be here next week. In the meantime, @lensman has left his in the Fablab as a stopgap.
