### ISSUE TITLE
Daniel: "familab site seems to be throwing a number of 403 errors over a Word Press plugin. It's contributing to more than a second and a half of load time issues with the site's main page."

### ISSUE THREAD

**Issue by willasaywhat** [familab/LabTasks#34]

**Comment by lancehudson** [comment]
What pages are exhibiting this? (works for me, signed in and signed out)

**Comment by lancehudson** [comment]
there are css files failing to load but they shouldnt cause the page to load slowly and are because the cdn is out of sync

**Comment by lancehudson** [comment]
toggling cdn seemed to get it to upload the files, i cannot use js or css minification without significant customization which will only break when other people install new plugins or possibly when plugins update. I did notice that the gif on our front page is 1.2 mb, so I'm compressing all the uploads. I added a plugin to auto compress when someone uploads something.
