### ISSUE TITLE
Laser optics are dirty; Power fades from left to right.

### ISSUE THREAD

**Issue by npolanosky** [familab/LabTasks#36]

**Comment by hybridsix** [comment]
Please be very careful with the optics, as they are extremely sensitive to scratches and the like. Generally no rubbing can be performed on the optics as it can damage the coating. There is a cleaning procedure outlined in the manual.

**Comment by npolanosky** [comment]
Fixed, cleaned according to manual with supplies in the side panel. Big difference, even power across the cut area now.
