### ISSUE TITLE
Famibot is sad

### ISSUE THREAD

**Issue by darkmoonsinger** [familab/LabTasks#38]

**Comment by willasaywhat** [comment]
So, Heroku kills famibot every 3 days or so. We need a better hosting solution for it, but I restarted it for now.

**Comment by Studnicky** [comment]
```
    setInterval(function herokukeepalive(){                 //  Ping Heroku every 10 minutes (600000ms)
        console.log('** Keepalive ping');
        http.get(process.env.KEEPALIVE_ENDPOINT);
    }, 600000);
```

**Comment by Studnicky** [comment]
Every 30 mins is fine. Heroku shuts down dynos that hear no web traffic, it doesn't consider bot traffic to be web traffic for whatever reason.
