### ISSUE TITLE
need ac filters for AC

### ISSUE THREAD

**Issue by omegatotal** [familab/LabTasks#43]

**Comment by lancehudson** [comment]
what size?

**Comment by omegatotal** [comment]
20x20 for the main ac, the fablab doesn't have one, not sure of size, maybe 14x20?

**Comment by lancehudson** [comment]
Grabbed a 20x20

**Comment by lancehudson** [comment]
20x24 is needed for main ac

**Comment by lancehudson** [comment]
We also need two 20x20's for the warehouse ac's

**Comment by jmcfly88** [comment]
I'll pick up some today and bring them in Tuesday.  I'm assuming 20x20x1

**Comment by lancehudson** [comment]
moved to #49
