### ISSUE TITLE
Wood bandsaw is broken. Motor power up but the blade doesn't move. -simply7

### ISSUE THREAD

**Issue by darkmoonsinger** [familab/LabTasks#53]

**Comment by DaveCasey** [comment]
I found the original woodruff key in some sawdust that fell out when I tipped it to take a look at it. I was going to take it apart, shim if needed, and replace the key, but dealin w the giant plotter was deemed more urgent.

**Comment by npolanosky** [comment]
In progress- Going to re-bore the hole, clean up the shaft, shim the bore, and add a new key.

**Comment by npolanosky** [comment]
Hole bored, keyway cleaned, shim added. Rick got a new blade for it. Back in action!
