### ISSUE TITLE
Misc Kitchen Needs

### ISSUE THREAD

**Issue by bradsilcox** [familab/LabTasks#7]
--K-cups and drawer organizer (or put these in the machine?)
--Tea + Coffee Accessories (sugar packets, creamer, etc) with holders and tiny trash can
--Sponge holder for the sink
--Soap dispenser for the sink
--Paper towel holder and paper towels for the sink

**Comment by willasaywhat** [comment]
I dropped off some K-cups and have ordered a "freedom clip" to liberate our Keurig from the evil overlords. I purchase the other things if that's cool with people. I think hybridsix mentioned we had paper towel dispensers already.

**Comment by willasaywhat** [comment]
This one is mostly done.
