### ISSUE TITLE
/broken and /needs commands are not working correctly in Slack

### ISSUE THREAD

**Issue by npolanosky** [familab/LabTasks#75]

**Comment by npolanosky** [comment]
![image](https://cloud.githubusercontent.com/assets/16981502/21370033/d18dac9a-c6d7-11e6-8dd1-200338ea913a.png)

**Comment by djchateau** [comment]
Token might be expired? @willasaywhat, it shows you as the one who set those commands up. Any feedback/insight?

**Comment by npolanosky** [comment]
This appears to be fixed
